### ISSUE TITLE
Crear conjunto de pruebas con POSTMAN en local

### ISSUE THREAD

**Issue by Sojer23** [Sojer23/fis18-06#14]

**Comment by carranza96** [comment]
Jose exporta esto  de postman que tienes a un ficherito y subelo al repo, y lo cierras

**Comment by Sojer23** [comment]
Conjunto de pruebas: 
- Compartido con el equipo
- Publicado en una URL: https://documenter.getpostman.com/view/1788279/RznBPLvL
- Adjuntado en la pestaña: Dev. Info
- Carpetas de prueba: HEROKU y LOCAL

Esto también sirve para tener una documentación, pero no sé si estaría mejor con Swagger.
