### ISSUE TITLE
Implementación del patrón circuit breaker

### ISSUE THREAD

**Issue by Sojer23** [Sojer23/fis18-06#36]
Este patrón se usa en las comunicaciones con otros servicios. 

Fue explicado en una de las últimas clases y esto es lo que tenía apuntado:
- CIRCUIT BREAKER
Si detecta que está haciendo llamadas y un MS no responde correctamente, el micro servicio que llama deja de hacer llamadas durante un tiempo para que no se saturen ambos microservicios. 
--Por primera vez se usó en netflix
-- Módulo: HystrixJS

![image](https://user-images.githubusercontent.com/10140897/50605821-cea76800-0ec3-11e9-91e4-685de9a93a85.png)

- Para hacerlo funcionar hay que crear un comando.
- Configurar la ventana temporal
- Configurar el timeout
- Configurar la llamada a la api
- SOLO EN EL CÓDIGO DEL CLIENTE

**Comment by pedrolarben** [comment]
Done
