### ISSUE TITLE
Mecanismo de autenticación a los métodos de la API

### ISSUE THREAD

**Issue by carranza96** [Sojer23/fis18-06#4]

**Comment by teramike** [comment]
Ahora la gente puede crearse un usuario y contraseña para nuestra api enviando un json estilo: {user:'nombreusuario',password:'sucontraseña'} con un post  a api/v1/comisiones/login, si el usuario no existe lo crea devuelve 201 y la apikey, si el usuario ya existia devuelve 200 y apikey.

**Comment by teramike** [comment]
Voy a implementar lo de la API key propia en las variables de entorno.

**Comment by teramike** [comment]
Deberia funcinar pero falta añadir la variable de entorno a nuestras llamadas ?apikey=process.env.APIKEY

**Comment by Sojer23** [comment]
Añadida la apikey a las peticiones desde nuestra app a nuestra API. El control de la seguridad no es el óptimo, pero funciona.
