### ISSUE TITLE
Añadir Pacto con Grupo 1 (Investigador)

### ISSUE THREAD

**Issue by Sojer23** [Sojer23/fis18-06#7]
Este grupo gestiona los investigadores y nuestros campos:
- investigadoresID
- sustitutoID

Nos lo tienen que proporcionar ellos.

**Comment by Sojer23** [comment]
Sobre los pactos tengo esto escrito de clase:

>Me sirve para facilitar la integración.
>Se define una especie de contacto entre cliente y proveedor.
>Sirve como documentación y poder desacoplar los desarrollos.

Los pactos son una especificación, que define el cliente, que incluye información sobre cómo espera recibir las peticiones.
- Se especifica en un conjunto de interacciones. 
  - Me permite que a partir de la creación del pacto me crea un proveedor Mock.
     - Cuando el cliente le pide /contacts, el siempre le devuelve los datos que se han definido en el pacto. 
     - Sirve para hacer pruebas unitarias del acceso del cliente al proveedor.
     - Además puedo lanzar un servidor en el que cuando haga peticiones se siga accediendo al proveedor Mock.
  - Todo esto se genera a partir del pacto.
Además, al crear un pacto para el proveedor se genera un verificador.
Comprueba que el proveedor devuelve lo establecido en el pacto.

**Comment by teramike** [comment]
No parece que esta gente nos pase nada de ids de los substitutos. De aquí lo que podemos hacer son consultar datos de nuestros investigadores por su DNI

**Comment by MichaelStevan** [comment]
(Por lo tanto el DNI se lo deberíamos pedir en el login de alguna forma.)

**Comment by teramike** [comment]
Ya está subido al server.
